# Generated by Django 2.1.4 on 2019-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Video_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment_text',
            field=models.TextField(max_length=150, verbose_name=''),
        ),
    ]
